### ISSUE TITLE
Mock-SASv2.1: The function "def isThereMoreThenOneValueInside(self,value):" in Assert.py is not working properly

### ISSUE THREAD

**Issue by ericzh31ericsson** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#18]
In Mock-SASv2.1, the function "def isThereMoreThenOneValueInside(self,value):" in Assert.py is not working when determine if there are multiple values in the parameters. especially when in the case of {"$or":["A","B"]}, or " {"$or":[["A"],["B"]]}. It gave the failure. 

I just made some work around to modify code as below:

        if("$or" in str(value)):
            strValue = str(value)            
            #print strValue
            
            indexOfOr= strValue.index("$or") 
            if indexOfOr <= 14
                return False

The idea here is that when '$or" is in the beginning of whole  
json object, then treat it as no multiple values inside. -- **_Of course this is just a workaround, please provide comments for more good solution._**

**Comment by awaizkhan** [comment]
Fixed in V3.

**Comment by ericzh31ericsson** [comment]
The issue is not fixed, Closed this one and open a new issue for Mock-SAS v3.0
